import PDFDocument from 'pdfkit';

export const generateRainwaterPDF = (assessmentData) => {
  return new Promise((resolve, reject) => {
    try {
      const doc = new PDFDocument();
      const chunks = [];
      
      doc.on('data', chunk => chunks.push(chunk));
      doc.on('end', () => resolve(Buffer.concat(chunks)));
      doc.on('error', reject);

      // Header
      doc.fontSize(20).fillColor('#0073e6').text('JalSarathi Water Management Report', 50, 50);
      doc.fontSize(12).fillColor('#666').text(`Generated on: ${new Date().toLocaleDateString()}`, 50, 80);
      
      // Assessment Details
      doc.fontSize(16).fillColor('#333').text('Assessment Details', 50, 120);
      doc.moveDown(0.5);
      
      doc.fontSize(10).fillColor('#333');
      doc.text(`Location: ${assessmentData.location}`, 50, doc.y);
      doc.text(`Rooftop Area: ${assessmentData.rooftopArea} m²`, 50, doc.y + 15);
      doc.text(`Building Type: ${assessmentData.buildingType}`, 50, doc.y + 15);
      doc.text(`Household Members: ${assessmentData.householdMembers}`, 50, doc.y + 15);
      
      // Results
      doc.moveDown(1);
      doc.fontSize(16).text('Results', 50, doc.y);
      doc.moveDown(0.5);
      
      const results = [
        `Harvestable Water: ${assessmentData.harvestableWater?.toLocaleString()} liters/year`,
        `Annual Savings: ₹${assessmentData.annualSavings?.toLocaleString()}`,
        `System Cost: ₹${assessmentData.systemCost?.toLocaleString()}`,
        `Payback Period: ${assessmentData.paybackPeriod} years`,
        `Water Demand Met: ${assessmentData.demandMetPercent}%`
      ];
      
      results.forEach((result, index) => {
        doc.text(result, 50, doc.y + (index * 15));
      });
      
      // Recommendations
      if (assessmentData.recommendations) {
        doc.moveDown(1);
        doc.fontSize(16).text('Recommendations', 50, doc.y);
        doc.moveDown(0.5);
        
        assessmentData.recommendations.forEach((rec, index) => {
          doc.text(`• ${rec}`, 50, doc.y + (index * 12));
        });
      }
      
      // Footer
      doc.fontSize(8).fillColor('#999').text(
        'Generated by JalSarathi - Smart Water Management Solution',
        50,
        doc.page.height - 50
      );
      
      doc.end();
    } catch (error) {
      reject(error);
    }
  });
};